### ISSUE TITLE
Incompatible with carpet 1.4.83 settings

### ISSUE THREAD

**Issue by MeeniMc** [manyrandomthings/minitweaks#26]
Mod version 1.19-1.3.1 (also marked compatible with MC 1.19.1) is incompatible with the 1.19.1 release of carpet (1.4.83).

For the error to be produced, a carpet.conf file created in a prior version (as when upgrading a world) must be present.

The following error is produced when reading the options (on world loading):
```
[16:23:08] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'carpet.settings.ParsedRule carpet.settings.ParsedRule.set(net.minecraft.class_2168, java.lang.String)'
	at minitweaks.MiniTweaks.lambda$onGameStarted$0(MiniTweaks.java:34) ~[minitweaks-1.19-1.3.1.jar:?]
	at carpet.settings.SettingsManager.lambda$addRuleObserver$0(SettingsManager.java:77) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
	at carpet.api.settings.SettingsManager.lambda$notifyRuleChanged$0(SettingsManager.java:265) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at carpet.api.settings.SettingsManager.notifyRuleChanged(SettingsManager.java:265) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
	at carpet.settings.ParsedRule.set(ParsedRule.java:305) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
	at carpet.settings.ParsedRule.set(ParsedRule.java:285) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
	at carpet.api.settings.SettingsManager.loadConfigurationFromConf(SettingsManager.java:421) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
	at carpet.api.settings.SettingsManager.attachServer(SettingsManager.java:281) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
	at carpet.CarpetServer.onServerLoaded(CarpetServer.java:93) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ebi000$serverLoaded(MinecraftServer.java:6786) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[16:23:08] [Server thread/ERROR]: This crash report has been saved to: C:\Games\Minecraft\MultiMC\instances\1.19.x\.minecraft\crash-reports\crash-2022-07-30_16.23.08-server.txt
[16:23:08] [Server thread/INFO]: Stopping server
[16:23:08] [Server thread/INFO]: Saving players
[16:23:08] [Server thread/INFO]: Saving worlds
[16:23:08] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "$$5" is null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:531) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:592) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3782(class_1132.java:195) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by manyrandomthings** [comment]
fixed in 1.3.2
